### ISSUE TITLE
Sync pack with latest version of Flarum

### ISSUE THREAD

**Issue by dshovchko** [eikoninaru/flarum-ext-ukrainian#10]
As a Ukrainian language pack consumer, I want to have a version of the pack compatible with the latest release of Flarum.

**Comment by dshovchko** [comment]
Created only to notify that I am currently in the process of upgrading to the current version (1.1.0). I plan to finish it within a few days.

**Comment by eikoninaru** [comment]
приємно чути)
можу допомогти з роботою:, скажіть, які файли чи рядки перекласти?

**Comment by dshovchko** [comment]
Найважче вже зробив - core та validation, а також flarum-tags.
Я так думаю що вже завтра або післязавтра все вже буде готово. Перевірю локально (бо вже є проапгреджена 1.1.1) та відкрию PR.

**Comment by dshovchko** [comment]
Може краще десь через якийсь час зробити нову версію? Або локалізацію для якихось розширень зробити?

**Comment by dshovchko** [comment]
Done. Synced and verified with last 1.1.1 version of Flarum

[PR](https://github.com/eikoninaru/flarum-ext-ukrainian/pull/11)

**Comment by dshovchko** [comment]
Я зробив адаптацію перекладу на поточну стабільну версію 1.1.1
Також додав переклади деяких розширень, з тих що я користуюся та можу перевірити переклад.
Ще виправив деякі переклади та оптимізував svg іконку.
composer.json також оновив бо підключав переклад напряму з моєї гілочки.

Чекаю на ваше рев’ю та реліз.

**Comment by eikoninaru** [comment]
> Я зробив адаптацію перекладу на поточну стабільну версію 1.1.1 Також додав переклади деяких розширень, з тих що я користуюся та можу перевірити переклад. Ще виправив деякі переклади та оптимізував svg іконку. composer.json також оновив бо підключав переклад напряму з моєї гілочки.
> 
> Чекаю на ваше рев’ю та реліз.

done
