### ISSUE TITLE
abandoned

### ISSUE THREAD

**Issue by luceos** [eikoninaru/flarum-ext-ukrainian#3]
Hello seems this language extension is not compatible with beta 6. I've marked the extension abandoned on the official forums, feel free to reply there after updating to put it back in the list.

https://discuss.flarum.org/d/2614-ukrainian-language-pack

**Comment by eikoninaru** [comment]
all work in beta6.
not translated some items, but fully compatible with beta 6)


![](https://i.imgur.com/FhvwQug.png)

**Comment by luceos** [comment]
Hello @eikoninaru we're currently at beta 7, does your language extension work with that version?

**Comment by eikoninaru** [comment]
Just right now wanted to update the translation)
